baseURL = "https://dotnetevangelist.net/"
languageCode = "zh-cn"
title = "Dotnet Evangelist"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "Fazrin"
description = "In solitude, where we are least alone."
github = "nirzaf"
linkedin = "mfmfazrin"
email = "mfmfazrin1986@gmail.com"
url = "https://dotnetevangelist.net/"
keywords = "blog, google analytics"
rss = true
lastmod = true
userStatusEmoji = "😀"
favicon = "https://avatars.githubusercontent.com/u/18024930?v=4"
location = "Qatar"
enableGitalk = true

[params.gitalk]
clientID = "Your client ID"
clientSecret = "Your client secret"
repo = "repo"
owner = "MeiK2333"
admin = "MeiK2333"
id = "location.pathname"
labels = "gitalk"
perPage = 15
pagerDirection = "last"
createIssueManually = true
distractionFreeMode = false

[[params.links]]
title = "Link"
href = "https://github.com/nirzaf"
[[params.links]]
title = "Link2"
href = "https://dotnetevangelist.net"
icon = "https://avatars.githubusercontent.com/u/18024930?v=4"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
