baseURL = "https://dotnetevangelist.net/"
languageCode = "zh-cn"
title = "Dotnet Evangelist"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "Fazrin"
description = "Passionate about making the end-user experience as seamless as possible"
github = "nirzaf"
linkedin = "mfmfazrin"
email = "mfmfazrin1986@gmail.com"
url = "https://dotnetevangelist.net/"
keywords = "dot net evangelist, mohamed, fazrin, farook, mfmfazrin, senior, software, engineer"
rss = false
showPostActivity = false
lastmod = true
userStatusEmoji = "😀"
favicon = "/images/favicon.ico"
location = "Qatar"
enableGitalk = false

perPage = 15
pagerDirection = "last"
createIssueManually = true
distractionFreeMode = true

[[params.links]]
title = "Link"
href = "https://nirzaf.github.io"
[[params.links]]
title = "Link2"
href = "https://dotnetevangelist.net"
icon = "https://avatars.githubusercontent.com/u/18024930?v=4"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
