baseURL = "https://dotnetevangelist.net"
languageCode = "zh-cn"
title = "Dotnet Evangelist"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "Fazrin"
description = "Passionate about making the end-user experience as seamless as possible"
github = "nirzaf"
linkedin = "mfmfazrin"
email = "info@dotnetevangelist.net"
hide_post_meta = true
url = "https://dotnetevangelist.net"
keywords = "dot net evangelist, mohamed, fazrin, farook, mfmfazrin, senior, software, engineer"
rss = false
lastmod = true
userStatusEmoji = "😀"
favicon = "https://res.cloudinary.com/dcx7eongu/image/upload/v1682878648/favicon_qwiwxi.ico"
location = "Qatar"
enableGitalk = false


perPage = 30
pagerDirection = "last"
createIssueManually = true
distractionFreeMode = true

[[params.links]]
title = "Link"
href = "https://nirzaf.github.io"
[[params.links]]
title = "Link2"
href = "https://dotnetevangelist.net"
icon = "https://res.cloudinary.com/dcx7eongu/image/upload/v1682878567/avatar_nqsosy.png"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
